In [30]:
import numpy as np

In [31]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [32]:
def sigmoid_der(x):
    return sigmoid(x)*(1-sigmoid(x))

In [33]:
#Initialising input and output:
inp = np.array([[0,1,0],
                [0,0,1],
                [1,0,0],
                [1,1,0],
                [1,1,1],
                [0,1,1],
                [0,1,0]])
target = np.array([[1,0,0,1,1,0,1]])
target = target.reshape(7,1)
print(inp)
print(target)


[[0 1 0]
 [0 0 1]
 [1 0 0]
 [1 1 0]
 [1 1 1]
 [0 1 1]
 [0 1 0]]
[[1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]]


In [45]:
np.random.seed(69)
weights = np.random.randn(3,1)
#weights = np.array(weights)
print(weights)
bias = np.random.rand(1)
print(bias)
lr = 0.01 #learning rate

[[ 0.9155071 ]
 [-0.60354197]
 [ 1.16229517]]
[0.56134898]


In [47]:
for epoch in range(5000):
    inputs = inp
    xw = np.dot(inputs,weights) + bias
    out = sigmoid(xw)
    error = target - out
    print(error.sum())
    der_cost = error
    der_pred = sigmoid_der(out)
    z_del = der_cost*der_pred
    inputs = inp.T
    weights = weights - lr*np.dot(inputs, z_del)
    for num in z_del:
        bias = bias - lr*num

-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
-3.0
